[book]
authors = ["cuihairu"]
language = "en"
src = "./"
title = "Hello Economics"

[build]
build-dir = "../hello-economics-book"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-css = ["css/katex.min.css"]
additional-js = ["js/katex.min.js", "js/auto-render.min.js", "js/katex-init.js", "js/mermaid.min.js", "js/mermaid-init.js"]
